services:
  primary:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-config/primary/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init.sql
      - primary-data:/var/lib/postgresql/data
  replica-sync:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-config/replica-sync/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - replica-sync-data:/var/lib/postgresql/data
    depends_on:
      - primary
  replica-async:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-config/replica-async/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - replica-async-data:/var/lib/postgresql/data
    depends_on:
      - primary
volumes:
  primary-data:
  replica-sync-data:
  replica-async-data:
