services:
  primary:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-config/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres-config/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init.sql
      - primary-data:/var/lib/postgresql/data
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
  replica-sync:
    image: postgres-slave:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
      SLOT_NAME: 'sync_slot'
      PGAPPNAME: 'replica-sync'
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-config/replica-sync/postgresql.conf:/etc/postgresql/postgresql.conf
      - replica-sync-data:/var/lib/postgresql/data
    command: './slave-init.sh'
    depends_on:
      - primary
  replica-async:
    image: postgres-slave:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
      SLOT_NAME: 'async_slot'
      PGAPPNAME: 'replica-async'
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-config/replica-async/postgresql.conf:/etc/postgresql/postgresql.conf
      - replica-async-data:/var/lib/postgresql/data
    command: './slave-init.sh' 
    depends_on:
      - primary
volumes:
  primary-data:
  replica-sync-data:
  replica-async-data:
